apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses: 
    - 192.168.100.40 - 192.168.100.42
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-pool
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: vm40
