apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: php
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "app_db"
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: php
