apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
    - name: nodejs
      image: baghdasaryanparis/nodev1:v1
      ports:
        - containerPort: 3000  
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: port1
