apiVersion: v1
kind: Pod
metadata:
  name: nodeminiserver
  labels:
    app: node-app
spec:
  containers:
    - name: node
      image: baghdasaryanparis/nodev1:v1
      ports:
        - containerPort: 3000
      env:
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort